add_rules("mode.release")

target("zest")
    set_kind("static")
    set_targetdir("lib")
    set_objectdir("obj")
    set_languages("c++11")
    add_files("zest/base/*.cc", "zest/net/*.cc")
    add_includedirs(".")
    set_optimize("fastest")
    add_syslinks("pthread")

target("echo_server")
    set_kind("binary")
    set_targetdir("bin")
    set_objectdir("obj")
    set_languages("c++11")
    add_files("example/echo_server.cc", "example/main.cc")
    add_includedirs(".")
    set_optimize("fastest")
    add_syslinks("pthread")
    add_deps("zest")

target("echo_client")
    set_kind("binary")
    set_targetdir("bin")
    set_objectdir("obj")
    set_languages("c++11")
    add_files("example/echo_client.cc")
    add_includedirs(".")
    set_optimize("fastest")
    add_syslinks("pthread")
    add_deps("zest")

target("echo_bench")
    set_kind("binary")
    set_targetdir("bin")
    set_objectdir("obj")
    set_languages("c++11")
    add_files("example/echo_bench.cc")
    add_includedirs(".")
    set_optimize("fastest")
    add_syslinks("pthread")
    add_deps("zest")
    